#!/usr/bin/env python3
"""Builds videos.js: every channel video that is about one of the tools in TOOLS.

Input:  data/channel-videos.tsv  (id, views, seconds, title, channel) - refresh with scripts/fetch-videos.sh
Output: videos.js                (loaded by the Videos tab only when it is opened)
        thumbs/<id>.jpg          (downloaded when missing, 320x180, so visitors never contact YouTube)

Run: python3 scripts/build-videos.py [--no-thumbs]
"""
import json, os, re, subprocess, sys, urllib.request, io
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Other ways a tool is written in video titles (lowercase). Tools not listed match on their name.
ALIASES = {
    "Proton VPN": ["proton vpn", "protonvpn"], "Proton Mail": ["proton mail", "protonmail"],
    "Proton Drive": ["proton drive"], "Proton Pass": ["proton pass"], "Opus Clip": ["opus clip", "opusclip"],
    "Murf AI": ["murf"], "Systeme.io": ["systeme.io", "systeme io", "systeme"], "Resume.io": ["resume.io"],
    "GoHighLevel": ["gohighlevel", "go high level", "highlevel"], "vidIQ": ["vidiq"],
    "Fiverr Pro": ["fiverr pro"], "Fiverr Logo Maker": ["fiverr logo maker", "fiverr logo"],
    "AT&T": ["at&t", "at&amp;t"], "Amigo eSIM": ["amigo esim", "amigo e-sim"], "Coda": ["coda.io", "coda"],
    "Epidemic Sound": ["epidemic sound", "epidemicsound"], "ElevenLabs": ["elevenlabs", "eleven labs"],
    "Merlin AI": ["merlin ai", "getmerlin", "merlin"], "TradingView": ["tradingview", "trading view"],
    "Talkpal": ["talkpal", "talk pal"], "Browse AI": ["browse ai", "browseai"],
}
# Titles that would undercut the affiliate offer or don't help a buyer: left out of the site.
EXCLUDE = re.compile(r"free alternative|alternatives?\b|for free|premium free|free premium|license key|crack|"
                     r"trial reset|without watermark|bypass|mod apk|\bhack|cancel|refund|delete (your |my )?account|"
                     r"unsubscribe|deactivate|close (your |my )?account|scam|wise ?agent", re.I)
SUFFIX = re.compile(r"\s*\|\s*(HTR|GG|Guide ?Glimpse|GuideG|Rocket Guide|HTRocket|How ?To ?Rocket)\s*$", re.I)


def read_js_array(src, name):
    i = src.index("const " + name + " =")
    j = src.index("];", i)
    return json.loads(subprocess.run(["node", "-e", "console.log(JSON.stringify(" + src[src.index("[", i):j + 1] + "))"],
                                     capture_output=True, text=True, check=True).stdout)


def main():
    src = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
    tools = read_js_array(src, "TOOLS")
    # Longer names first, so "Fiverr Pro" wins over "Fiverr".
    keys = []
    for t in tools:
        for k in ALIASES.get(t["name"], [t["name"].lower()]):
            keys.append((k, t["name"]))
    keys.sort(key=lambda k: -len(k[0]))
    patterns = [(re.compile(r"(?<![a-z0-9])" + re.escape(k) + r"(?![a-z0-9])"), name) for k, name in keys]

    curated = {re.search(r"v=([\w-]{11})", v["url"]).group(1) for v in read_js_array(src, "VIDEOS")}
    rows, seen = [], set()
    for line in open(os.path.join(ROOT, "data/channel-videos.tsv"), encoding="utf-8"):
        p = line.rstrip("\n").split("\t")
        if len(p) < 5 or p[0] in seen:
            continue
        vid, views, secs, title, channel = p[0], p[1], p[2], p[3], p[4]
        seen.add(vid)
        try:
            if 0 < float(secs) <= 60:      # Shorts are left out
                continue
        except ValueError:
            pass
        if vid in curated or EXCLUDE.search(title):
            continue
        tl = " " + title.lower() + " "
        tool = next((name for rx, name in patterns if rx.search(tl)), None)
        if not tool:
            continue
        rows.append((int(views) if views.isdigit() else 0, vid, SUFFIX.sub("", title).strip(), channel, tool))
    rows.sort(key=lambda r: -r[0])

    channels = sorted({r[3] for r in rows})
    tool_names = [t["name"] for t in tools]
    data = [[r[1], r[2], channels.index(r[3]), tool_names.index(r[4])] for r in rows]
    with open(os.path.join(ROOT, "videos.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build-videos.py from data/channel-videos.tsv. Do not edit by hand.\n")
        f.write("// [video id, title, channel index, tool index in TOOLS], most viewed first.\n")
        f.write("window.CHANNEL_VIDEO_CHANNELS = " + json.dumps(channels) + ";\n")
        f.write("window.CHANNEL_VIDEO_TOOLS = " + json.dumps(tool_names, ensure_ascii=False) + ";\n")
        f.write("window.CHANNEL_VIDEOS = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(len(rows), "videos written to videos.js")

    if "--no-thumbs" not in sys.argv:
        fetch_thumbs([r[1] for r in rows])


def fetch_thumbs(ids):
    from PIL import Image
    os.makedirs(os.path.join(ROOT, "thumbs"), exist_ok=True)
    todo = [i for i in ids if not os.path.exists(os.path.join(ROOT, "thumbs", i + ".jpg"))]

    def one(vid):
        try:
            raw = urllib.request.urlopen("https://i.ytimg.com/vi/%s/mqdefault.jpg" % vid, timeout=30).read()
            im = Image.open(io.BytesIO(raw)).convert("RGB").resize((320, 180))
            im.save(os.path.join(ROOT, "thumbs", vid + ".jpg"), quality=72, optimize=True, progressive=True)
            return True
        except Exception:
            return False
    with ThreadPoolExecutor(12) as ex:
        ok = sum(ex.map(one, todo))
    print("thumbnails downloaded:", ok, "of", len(todo))


if __name__ == "__main__":
    main()
